// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test_AssFinal_05.Models;

#nullable disable

namespace Test_AssFinal_05.Migrations
{
    [DbContext(typeof(KHHV_Test05Context))]
    partial class KHHV_Test05ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Test_AssFinal_05.Models.HocVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChuyenNganh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tuoi")
                        .HasColumnType("int");

                    b.Property<string>("khoaHocMaKhoaHoc")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("khoaHocMaKhoaHoc");

                    b.ToTable("HocViens");
                });

            modelBuilder.Entity("Test_AssFinal_05.Models.KhoaHoc", b =>
                {
                    b.Property<string>("MaKhoaHoc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NamHoc")
                        .HasColumnType("int");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhoaHoc");

                    b.ToTable("khoaHocs");
                });

            modelBuilder.Entity("Test_AssFinal_05.Models.HocVien", b =>
                {
                    b.HasOne("Test_AssFinal_05.Models.KhoaHoc", "khoaHoc")
                        .WithMany("HocViens")
                        .HasForeignKey("khoaHocMaKhoaHoc");

                    b.Navigation("khoaHoc");
                });

            modelBuilder.Entity("Test_AssFinal_05.Models.KhoaHoc", b =>
                {
                    b.Navigation("HocViens");
                });
#pragma warning restore 612, 618
        }
    }
}
