// <auto-generated />
using BangntPH30138.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BangntPH30138.Migrations
{
    [DbContext(typeof(bangntph30138Context))]
    partial class bangntph30138ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BangntPH30138.Models.CanHo", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("DienTich")
                        .HasColumnType("float");

                    b.Property<string>("So")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToaNhaID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ToaNhaID");

                    b.ToTable("CanHos");
                });

            modelBuilder.Entity("BangntPH30138.Models.ToaNha", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ToaNhas");
                });

            modelBuilder.Entity("BangntPH30138.Models.CanHo", b =>
                {
                    b.HasOne("BangntPH30138.Models.ToaNha", "ToaNha")
                        .WithMany("CanHos")
                        .HasForeignKey("ToaNhaID");

                    b.Navigation("ToaNha");
                });

            modelBuilder.Entity("BangntPH30138.Models.ToaNha", b =>
                {
                    b.Navigation("CanHos");
                });
#pragma warning restore 612, 618
        }
    }
}
